import type { Project } from "@/types";

const createdAt = "2026-06-09T00:00:00.000Z";

export const sampleProject: Project = {
  id: "sample-laptop-moora",
  name: "Pemilihan Laptop Terbaik (Contoh)",
  description: "Contoh penggunaan SPK MOORA untuk memilih laptop",
  createdAt,
  updatedAt: createdAt,
  criteria: [
    {
      id: "c-harga",
      code: "C1",
      name: "Harga",
      type: "cost",
      weight: 0.3,
    },
    {
      id: "c-ram",
      code: "C2",
      name: "RAM",
      type: "benefit",
      weight: 0.25,
    },
    {
      id: "c-storage",
      code: "C3",
      name: "Storage",
      type: "benefit",
      weight: 0.2,
    },
    {
      id: "c-cpu",
      code: "C4",
      name: "Performa CPU",
      type: "benefit",
      weight: 0.15,
    },
    {
      id: "c-baterai",
      code: "C5",
      name: "Baterai (jam)",
      type: "benefit",
      weight: 0.1,
    },
  ],
  alternatives: [
    { id: "a-laptop-a", code: "A1", name: "Laptop A" },
    { id: "a-laptop-b", code: "A2", name: "Laptop B" },
    { id: "a-laptop-c", code: "A3", name: "Laptop C" },
    { id: "a-laptop-d", code: "A4", name: "Laptop D" },
    { id: "a-laptop-e", code: "A5", name: "Laptop E" },
  ],
  values: [
    { alternativeId: "a-laptop-a", criteriaId: "c-harga", value: 12000 },
    { alternativeId: "a-laptop-a", criteriaId: "c-ram", value: 16 },
    { alternativeId: "a-laptop-a", criteriaId: "c-storage", value: 512 },
    { alternativeId: "a-laptop-a", criteriaId: "c-cpu", value: 85 },
    { alternativeId: "a-laptop-a", criteriaId: "c-baterai", value: 8 },
    { alternativeId: "a-laptop-b", criteriaId: "c-harga", value: 9500 },
    { alternativeId: "a-laptop-b", criteriaId: "c-ram", value: 8 },
    { alternativeId: "a-laptop-b", criteriaId: "c-storage", value: 256 },
    { alternativeId: "a-laptop-b", criteriaId: "c-cpu", value: 72 },
    { alternativeId: "a-laptop-b", criteriaId: "c-baterai", value: 10 },
    { alternativeId: "a-laptop-c", criteriaId: "c-harga", value: 15000 },
    { alternativeId: "a-laptop-c", criteriaId: "c-ram", value: 32 },
    { alternativeId: "a-laptop-c", criteriaId: "c-storage", value: 1024 },
    { alternativeId: "a-laptop-c", criteriaId: "c-cpu", value: 95 },
    { alternativeId: "a-laptop-c", criteriaId: "c-baterai", value: 6 },
    { alternativeId: "a-laptop-d", criteriaId: "c-harga", value: 11000 },
    { alternativeId: "a-laptop-d", criteriaId: "c-ram", value: 16 },
    { alternativeId: "a-laptop-d", criteriaId: "c-storage", value: 512 },
    { alternativeId: "a-laptop-d", criteriaId: "c-cpu", value: 78 },
    { alternativeId: "a-laptop-d", criteriaId: "c-baterai", value: 9 },
    { alternativeId: "a-laptop-e", criteriaId: "c-harga", value: 8000 },
    { alternativeId: "a-laptop-e", criteriaId: "c-ram", value: 8 },
    { alternativeId: "a-laptop-e", criteriaId: "c-storage", value: 256 },
    { alternativeId: "a-laptop-e", criteriaId: "c-cpu", value: 65 },
    { alternativeId: "a-laptop-e", criteriaId: "c-baterai", value: 12 },
  ],
  snapshots: [],
  methods: ["MOORA", "SAW", "TOPSIS", "AHP", "WP"],
};
